### ISSUE TITLE
ValueError: Expected scalar shape, saw shape: (1,).

### ISSUE THREAD

**Issue by jewaliddin123** [anita-hu/TF2_RL#4]
At first thank you Anita -hu for providing code. i am executing AEDDPG code ,with continuous Action space gym environments ,i am getting following error .kindly help solving the error.

self.action_space=spaces.Box(low=-1,high=1,shape=(1,),dtype=np.float32)
 
 File "TF2_AE_DDPG.py", line 212, in async_collection
    tf.summary.scalar('Stats/action', action, step=total_steps)
  File "C:\New folder\envs\test\lib\site-packages\tensorboard\plugins\scalar\summary_v2.py", line 61, in scalar
    tf.debugging.assert_scalar(data)
  File "C:\New folder\envs\test\lib\site-packages\tensorflow_core\python\ops\check_ops.py", line 2068, in assert_scalar_v2
    assert_scalar(tensor=tensor, message=message, name=name)
  File "C:\New folder\envs\test\lib\site-packages\tensorflow_core\python\ops\check_ops.py", line 2098, in assert_scalar
    % (message or '', shape,))
ValueError: Expected scalar shape, saw shape: (1,).

**Comment by anita-hu** [comment]
When logging the action, tensorboard expected a scalar which means shape () but it received shape (1,). Try changing the code in line [211](https://github.com/anita-hu/TF2-RL/blob/master/AE-DDPG/TF2_AE_DDPG.py#L211) to be `tf.summary.scalar('Stats/action', action[0], step=total_steps)`. Hopefully that fixes it 🙂 

If you are working with actions that have shape greater than 1, you can just comment out that code and not log the actions or log each value separately in a for loop

**Comment by jewaliddin123** [comment]
Thank you anita hu for your valuable response.
