### ISSUE TITLE
Help regarding pushing code on GPU

### ISSUE THREAD

**Issue by jewaliddin123** [anita-hu/TF2_RL#6]
Hi Anita hu,
               I am Jewaliddinn shaik doing Ph.D  from NIT AP,india . I need to force AE_DDPG code to work on GPU mode .kindly suggest me which lines modifications need in code. thank you in advance awaiting for positive response.

**Comment by anita-hu** [comment]
Based on [this](https://wandb.ai/authors/ayusht/reports/Using-GPUs-With-Keras-A-Tutorial-With-Code--VmlldzoxNjEyNjE), "If a TensorFlow operation has both CPU and GPU implementations, by default the GPU will be used by default. So we don't need to change anything about our training pipeline to use a GPU."
You can check if you have gpu access with `print('GPU name: ', tf.config.experimental.list_physical_devices('GPU'))`. If you don't see gpus, make sure you have installed tensorflow with GPU setup, some instructions [here](https://www.tensorflow.org/install/pip)
Not sure if you've tried out directly running the code on gpu. Let me know if you hit any issues

**Comment by jewaliddin123** [comment]
thank you anita hu for kind response, i tried to run code with your feed
back.code is able to see GPU but not utilising gpu when i check in
nvidia-smi .i need one small information that is numpy work with gpu ?
because NN model is created with np operation .is np may be issue for not
accessing gpu ?kindly give me clarity.

**Comment by anita-hu** [comment]
Yes using numpy might be the issue, try replacing anywhere that uses numpy functions or variables with the corresponding tensorflow one

**Comment by jewaliddin123** [comment]
Thank you anita hu for your kind valuable response. I will try to do
modifications
